### ISSUE TITLE
Map Search: open links in new window/tab

### ISSUE THREAD

**Issue by baxter-brad** [mksndz/meta#28]
When I click a number in Map Search and see "View items from
this location" in the thought balloon, can you make that link opens in
a new window (e.g., target="_blank")?  This will help when I'm
browsing around in a particular area and want to return to where I
was.

Using the back button to return to the map always resets it to full
zoom out.  I know I can right click and choose to open in a new tab,
but I'd like it to work that way all the time.

**Comment by mksndz** [comment]
I've enabled this as an option by adding an additional link.

See:

375235af704e61f589bfedd56eea4f2bab9b0d73
362b07ff2e3bff21f8542053cb61f1879af39507
