### ISSUE TITLE
Add dcterms:identifier to metadata displays

### ISSUE THREAD

**Issue by baxter-brad** [mksndz/meta#34]
I think that dcterms:identifier needs to appear with the other metadata in item displays, e.g.

http://metaweb.galib.uga.edu/solr_documents/ugabma_gfc_gfc-2286-01

Also, I'd like for it to be hyperlinked to itself (maybe that's automatic for URLs?)

**Comment by mksndz** [comment]
An oversight on my part led to the dcterms_identifier field not being indexed. This should be addressed on the next import.

Regarding linking, I see that many items have identifier values that are not URLs. See: gsu_ajc_3177, so I can't always make this field a link
